# Generated by Django 3.1.1 on 2020-10-29 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0003_auto_20201029_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='static/articulos/img/articulos'),
        ),
    ]
