# Generated by Django 3.1.2 on 2020-11-10 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0004_auto_20201029_0013'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=30)),
                ('sexo', models.CharField(max_length=1)),
                ('contraseña', models.CharField(max_length=15)),
                ('edad', models.IntegerField(max_length=2)),
                ('img', models.ImageField(blank=True, null=True, upload_to='static/articulos/img/usuarios')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
    ]
