# Generated by Django 3.1.2 on 2020-11-10 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0006_auto_20201110_2005'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['nombreUsuario']},
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='nombre',
            new_name='nombreUsuario',
        ),
    ]
