# Generated by Django 3.1.2 on 2020-11-11 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0007_auto_20201110_2048'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sexo', models.CharField(help_text='Añada descripción del tipo sexo', max_length=50)),
            ],
            options={
                'ordering': ['sexo'],
            },
        ),
        migrations.AlterField(
            model_name='usuario',
            name='sexo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articulos.sexo'),
        ),
    ]
