# Generated by Django 3.1.1 on 2020-12-06 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0008_auto_20201110_2232'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={},
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='contraseña',
        ),
        migrations.AddField(
            model_name='usuario',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='password',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='usuarioActivo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='usuarioAdmin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=30, unique=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='static/articulos/img/usuarios', verbose_name='Imagen de Perfil'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombreUsuario',
            field=models.CharField(max_length=100, verbose_name='Nombre de usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(max_length=12, verbose_name='Telefono'),
        ),
    ]
